# Generated by Django 5.1.2 on 2024-10-20 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('estimated_duration', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('rut_technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.technician')),
            ],
            options={
                'unique_together': {('rut_technician', 'id_service')},
            },
        ),
    ]
