# Generated by Django 5.1.2 on 2024-12-15 20:06

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='cv',
            field=models.FileField(default=None, upload_to=apps.users.models.get_cv_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='letter',
            field=models.FileField(default=None, upload_to=apps.users.models.get_letter_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technician',
            name='title',
            field=models.FileField(default=None, upload_to=apps.users.models.get_title_path),
            preserve_default=False,
        ),
    ]
