# Generated by Django 5.1.2 on 2024-10-17 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="id_status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="requests.requeststatus",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="technician_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.technicianservice",
            ),
        ),
    ]
