# Generated by Django 5.1.2 on 2024-12-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='customer_comment',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='request',
            name='technician_comment',
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('request', 'technician')},
        ),
        migrations.AlterUniqueTogether(
            name='quotationservice',
            unique_together={('quotation', 'service')},
        ),
    ]
