# Generated by Django 5.1.2 on 2024-12-15 20:06

import apps.requests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_rename_customer_comment_request_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_image',
            field=models.ImageField(default=None, upload_to=apps.requests.models.get_image_path),
            preserve_default=False,
        ),
    ]
